version: '3.7'
services:
    my_app:
        container_name: my_app
        build: infra
        ports:
            - "8000:8000"
        restart: always
        expose:
            - 9003
        volumes:
            - .:/var/www/html
            - ./infra/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./infra/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini